Name:           ros-jade-rqt-ez-publisher
Version:        0.3.1
Release:        0%{?dist}
Summary:        ROS rqt_ez_publisher package

Group:          Development/Libraries
License:        BSD
URL:            http://wiki.ros.org/rqt_ez_publisher
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-jade-geometry-msgs
Requires:       ros-jade-rospy
Requires:       ros-jade-rqt-gui
Requires:       ros-jade-rqt-gui-py
Requires:       ros-jade-rqt-py-common
Requires:       ros-jade-tf
Requires:       ros-jade-tf2-msgs
BuildRequires:  python-catkin_pkg
BuildRequires:  ros-jade-catkin
BuildRequires:  ros-jade-rostest
BuildRequires:  ros-jade-sensor-msgs

%description
The rqt_ez_publisher package

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/jade" \
        -DCMAKE_PREFIX_PATH="/opt/ros/jade" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/jade

%changelog
* Tue Apr 12 2016 Takashi Ogura <t.ogura@gmail.com> - 0.3.1-0
- Autogenerated by Bloom

* Mon Apr 11 2016 Takashi Ogura <t.ogura@gmail.com> - 0.3.0-1
- Autogenerated by Bloom

* Sat May 02 2015 Takashi Ogura <t.ogura@gmail.com> - 0.3.0-0
- Autogenerated by Bloom

